server:
  port: 20001
  error:
    include-message: always

spring:
  application:
    name: coupon-calculation-serv

logging:
  level:
    com.geekbang.coupon.calculation: debug

spring.output.ansi.enabled: always

management:
  endpoints:
    web:
      exposure:
        include: "*"